import csv
import hashlib
import io
import json

import pytest

from rc_bridge.core.models import BridgeGeometry, ProjectInput, SupportSystem
from rc_bridge.export.verification_package import build_verification_export_package
from rc_bridge.workflow.project_continuous import (
    GlobalBeamPointLoad,
    ProjectContinuousLoadCase,
    run_project_continuous_load_case,
)
from rc_bridge.workflow.verification_export import build_project_continuous_verification_model


def _project_and_case() -> tuple[ProjectInput, ProjectContinuousLoadCase]:
    project = ProjectInput(
        name="Verification Package Bridge",
        geometry=BridgeGeometry(
            span_lengths_m=[10.0, 12.0],
            support_system=SupportSystem.CONTINUOUS,
        ),
    )
    load_case = ProjectContinuousLoadCase(
        ei_kn_m2_by_span=(1.0e6, 1.2e6),
        udl_kn_m_by_span=(20.0, 25.0),
        point_loads=(GlobalBeamPointLoad(100.0, 5.0, "verification axle"),),
        name="service verification",
    )
    return project, load_case


def test_verification_package_contains_models_manifest_and_expected_results() -> None:
    project, load_case = _project_and_case()
    analysis = run_project_continuous_load_case(project, load_case)
    model = build_project_continuous_verification_model(
        project,
        load_case,
        analysis_area_m2_by_span=(0.45, 0.45),
    )
    package = build_verification_export_package(model, analysis)

    assert package.midas_mct.startswith("; Generated by RC-Bridge-Analysis-ANN")
    assert package.staad_std.startswith("STAAD SPACE")

    manifest = json.loads(package.manifest_json)
    assert manifest["schema_version"] == 1
    assert manifest["model_name"] == model.name
    assert manifest["units"] == {"length": "m", "force": "kN", "moment": "kNm"}
    assert manifest["node_count"] == 3
    assert manifest["member_count"] == 2
    assert manifest["load_cases"] == ["service verification"]
    assert manifest["files"]["midas_mct"]["sha256"] == hashlib.sha256(
        package.midas_mct.encode("utf-8")
    ).hexdigest()
    assert manifest["files"]["staad_std"]["sha256"] == hashlib.sha256(
        package.staad_std.encode("utf-8")
    ).hexdigest()
    assert manifest["files"]["expected_results_csv"]["sha256"] == hashlib.sha256(
        package.expected_results_csv.encode("utf-8")
    ).hexdigest()

    rows = list(csv.DictReader(io.StringIO(package.expected_results_csv)))
    result_types = {row["result_type"] for row in rows}
    assert {
        "support_reaction",
        "support_rotation",
        "member_end_force",
        "span_envelope",
        "span_deflection",
    }.issubset(result_types)
    assert any(row["component"] == "M_max_sagging" for row in rows)
    assert any(row["component"] == "DZ_max_abs" for row in rows)


def test_verification_package_expected_results_match_internal_reactions() -> None:
    project, load_case = _project_and_case()
    analysis = run_project_continuous_load_case(project, load_case)
    model = build_project_continuous_verification_model(
        project,
        load_case,
        analysis_area_m2_by_span=(0.45, 0.45),
    )
    package = build_verification_export_package(model, analysis)

    rows = list(csv.DictReader(io.StringIO(package.expected_results_csv)))
    reaction_rows = [row for row in rows if row["result_type"] == "support_reaction"]
    assert len(reaction_rows) == len(analysis.solution.nodes)
    for row, node in zip(reaction_rows, analysis.solution.nodes, strict=True):
        assert int(row["object_id"]) == node.node_index + 1
        assert float(row["value"]) == node.vertical_reaction_kn
        assert row["unit"] == "kN"


def test_verification_package_exposes_four_named_user_files() -> None:
    project, load_case = _project_and_case()
    analysis = run_project_continuous_load_case(project, load_case)
    model = build_project_continuous_verification_model(
        project,
        load_case,
        analysis_area_m2_by_span=(0.45, 0.45),
    )
    package = build_verification_export_package(model, analysis)

    files = package.files("two span check")
    assert set(files) == {
        "two_span_check.mct",
        "two_span_check.std",
        "two_span_check_manifest.json",
        "two_span_check_expected_results.csv",
    }
    assert files["two_span_check.mct"] == package.midas_mct
    assert files["two_span_check.std"] == package.staad_std


def test_verification_package_rejects_mismatched_expected_analysis() -> None:
    project, load_case = _project_and_case()
    model = build_project_continuous_verification_model(
        project,
        load_case,
        analysis_area_m2_by_span=(0.45, 0.45),
    )
    different_case = ProjectContinuousLoadCase(
        ei_kn_m2_by_span=(1.0e6, 1.2e6),
        udl_kn_m_by_span=(20.0, 25.0),
        name="different load case",
    )
    analysis = run_project_continuous_load_case(project, different_case)

    with pytest.raises(ValueError, match="same load-case name"):
        build_verification_export_package(model, analysis)
