from __future__ import annotations

import math
import re

from rc_bridge.export.verification_model import VerificationModel


def _safe_name(value: str) -> str:
    text = re.sub(r"[^A-Za-z0-9_ -]", "_", value.strip())
    return text[:40] or "ITEM"


def _equivalent_display_dimensions(area_m2: float, inertia_m4: float) -> tuple[float, float]:
    """Return positive rectangle dimensions used only for MIDAS section display metadata.

    The actual analysis properties are written explicitly on the VALUE-section
    property line. These dimensions therefore do not define the verification
    stiffness; they keep the MCT section record physically well formed.
    """
    depth = math.sqrt(12.0 * inertia_m4 / area_m2)
    width = area_m2 / depth
    return width, depth


def export_midas_mct(model: VerificationModel) -> str:
    """Render a MIDAS Civil ``.mct`` verification model in kN-m units."""
    model.validate_load_positions()
    lines: list[str] = [
        "; Generated by RC-Bridge-Analysis-ANN verification exporter",
        "*UNIT",
        "kN, m",
        "*PROJINFO",
        f"PROJECT={_safe_name(model.name)}, TITLE=Independent verification model",
        "*NODE",
    ]
    lines.extend(
        f"{node.node_id}, {node.x_m:.12g}, {node.y_m:.12g}, {node.z_m:.12g}"
        for node in model.nodes
    )

    lines.append("*MATERIAL")
    for material in model.materials:
        lines.append(
            f"{material.material_id}, CONC, {_safe_name(material.name)}, 0, 0, 2, "
            f"{material.elastic_modulus_kn_m2:.12g}, {material.poisson_ratio:.12g}, "
            f"{material.thermal_expansion_per_c:.12g}, {material.weight_density_kn_m3:.12g}"
        )

    lines.append("*SECTION")
    for section in model.sections:
        width, depth = _equivalent_display_dimensions(
            section.area_m2,
            max(section.iy_m4, section.iz_m4),
        )
        asy = section.shear_area_y_m2 or section.area_m2
        asz = section.shear_area_z_m2 or section.area_m2
        perimeter = 2.0 * (width + depth)
        section_header = (
            f"{section.section_id}, VALUE, {_safe_name(section.name)}, CC, SB, Built, "
            f"{width:.12g}, {depth:.12g}, 0, 0, 0, 0"
        )
        section_properties = (
            f"{section.area_m2:.12g}, {asy:.12g}, {asz:.12g}, "
            f"{section.torsion_constant_m4:.12g}, {section.iy_m4:.12g}, {section.iz_m4:.12g}"
        )
        section_geometry = (
            f"{width / 2.0:.12g}, {width / 2.0:.12g}, {depth / 2.0:.12g}, "
            f"{depth / 2.0:.12g}, 0, 0, {perimeter:.12g}, 0, "
            f"{width / 2.0:.12g}, {depth / 2.0:.12g}"
        )
        lines.extend(
            [
                section_header,
                section_properties,
                section_geometry,
                "0, 0, 0, 0, 0, 0, 0, 0",
            ]
        )

    lines.append("*ELEMENT")
    lines.extend(
        f"{beam.member_id}, BEAM, {beam.material_id}, {beam.section_id}, "
        f"{beam.node_i}, {beam.node_j}, {beam.beta_angle_deg:.12g}"
        for beam in model.beams
    )

    if model.supports:
        lines.append("*CONSTRAINT")
        lines.extend(f"{support.node_id}, {support.restraint_code}" for support in model.supports)

    if model.load_cases:
        lines.append("*STLDCASE")
        lines.extend(f"{_safe_name(case.name)}, USER, verification load case" for case in model.load_cases)

    for case in model.load_cases:
        case_name = _safe_name(case.name)
        lines.extend(["*USE-STLD", case_name])
        if case.self_weight_gz_factor != 0.0:
            lines.extend(["*SELFWEIGHT", f"0, 0, {case.self_weight_gz_factor:.12g}"])
        if case.uniform_loads or case.point_loads:
            lines.append("*BEAMLOAD")
            for load in case.uniform_loads:
                member_length = model.member_length_m(load.member_id)
                start = 0.0 if load.start_m is None else load.start_m
                end = member_length if load.end_m is None else load.end_m
                lines.append(
                    f"{load.member_id}, BEAM, UNILOAD, {load.direction}, NO, "
                    f"{start:.12g}, {load.magnitude_kn_m:.12g}, "
                    f"{end:.12g}, {load.magnitude_kn_m:.12g}"
                )
            for load in case.point_loads:
                lines.append(
                    f"{load.member_id}, BEAM, CONLOAD, {load.direction}, NO, "
                    f"{load.distance_from_i_m:.12g}, {load.magnitude_kn:.12g}"
                )
        if case.nodal_loads:
            lines.append("*CONLOAD")
            for load in case.nodal_loads:
                lines.append(
                    f"{load.node_id}, {load.fx_kn:.12g}, {load.fy_kn:.12g}, "
                    f"{load.fz_kn:.12g}, {load.mx_knm:.12g}, {load.my_knm:.12g}, "
                    f"{load.mz_knm:.12g}"
                )

    lines.append("*ENDDATA")
    return "\n".join(lines) + "\n"
